/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_suitang_JniCall */

#ifndef _Included_com_game_suitang_JniCall
#define _Included_com_game_suitang_JniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_suitang_JniCall
 * Method:    jniOpt
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_game_suitang_JniCall_jniOpt
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
