/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_suitang_JniHelper */

#ifndef _Included_com_game_suitang_JniHelper
#define _Included_com_game_suitang_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_suitang_JniHelper
 * Method:    setbar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_game_suitang_JniHelper_setbar
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_game_suitang_JniHelper
 * Method:    setPackageName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_game_suitang_JniHelper_setPackageName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_game_suitang_JniHelper
 * Method:    callToRefresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_suitang_JniHelper_callToRefresh
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
