CONFIG_SCREEN_WIDTH  = 480
CONFIG_SCREEN_HEIGHT = 854


CONFIG_HOST = "http://android-shuihu.huanleya.com"
CONFIG_HTTP_URL = "http://xu850527.oicp.net:1995/"
CONFIG_SOCKET_HOST = "169.254.28.29"
CONFIG_SOCKET_PORT = 1234


IMAGEBUTTON = 0--图片按钮
TEXTBUTTON = 1--文本按钮
IMAGEPATH = "image"--资源路径

COMMONPATH = "image/common/"
